[package]
name = "sync-that-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
dittolive-ditto.path = "/home/robert/source/ditto/rust/dittolive-ditto"
serde_json = "1.0.128"
tokio = "1.40.0"
